name: CodeQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Add google-services.json
      env:
        JSON: ${{ secrets.GOOGLESERVICESJSON }}
      run: echo $JSON > app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run detekt
      run: ./gradlew detekt

