name: Unit and instrumented tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests with Gradle
      run: ./gradlew createDebugUnitTestCoverageReport
      
    - name: Run instrumented tests with Gradle
      uses: vgaidarji/android-github-actions-emulator@v1.0.1
      with:
        api-level: 29
        target: google_apis
        arch: x86_64
        script: ./gradlew createDebugAndroidTestCoverageReport

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3

